language: java

jdk:
  - openjdk7
  - oraclejdk8
  - openjdk8
  - oraclejdk10
  - openjdk10

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6.3.0
  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew classes testClasses

script: ./gradlew test --stacktrace --no-daemon

